extends RefCounted
class_name DFMaterials



# Auto-generated from Dwarf Fortress raw data
# 265 entries

static func get_all() -> Array:
	return [
		{
			"id": "IRON",
			"name": "Iron",
			"color": "#555555",
			"value": 10,
			"type": "metal",
		},
		{
			"id": "GOLD",
			"name": "Gold dust",
			"color": "#FFFF55",
			"value": 30,
			"type": "metal",
		},
		{
			"id": "SILVER",
			"name": "Silver",
			"color": "#FFFFFF",
			"value": 10,
			"type": "metal",
		},
		{
			"id": "COPPER",
			"name": "Copper",
			"color": "#AA5500",
			"value": 2,
			"type": "metal",
		},
		{
			"id": "NICKEL",
			"name": "Nickel",
			"color": "#AAAAAA",
			"value": 2,
			"type": "metal",
		},
		{
			"id": "ZINC",
			"name": "Zinc",
			"color": "#AAAAAA",
			"value": 2,
			"type": "metal",
		},
		{
			"id": "BRONZE",
			"name": "Bronze",
			"color": "#AA5500",
			"value": 5,
			"type": "metal",
		},
		{
			"id": "BRASS",
			"name": "Brass",
			"color": "#FFFF55",
			"value": 7,
			"type": "metal",
		},
		{
			"id": "STEEL",
			"name": "Steel",
			"color": "#555555",
			"value": 30,
			"type": "metal",
		},
		{
			"id": "PIG_IRON",
			"name": "Pig iron",
			"color": "#555555",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "PLATINUM",
			"name": "Platinum",
			"color": "#FFFFFF",
			"value": 40,
			"type": "metal",
		},
		{
			"id": "ELECTRUM",
			"name": "Electrum",
			"color": "#FFFF55",
			"value": 20,
			"type": "metal",
		},
		{
			"id": "TIN",
			"name": "Tin",
			"color": "#AAAAAA",
			"value": 2,
			"type": "metal",
		},
		{
			"id": "PEWTER_FINE",
			"name": "Fine pewter",
			"color": "#FFFFFF",
			"value": 5,
			"type": "metal",
		},
		{
			"id": "PEWTER_TRIFLE",
			"name": "Trifle pewter",
			"color": "#AAAAAA",
			"value": 4,
			"type": "metal",
		},
		{
			"id": "PEWTER_LAY",
			"name": "Lay pewter",
			"color": "#00AAAA",
			"value": 3,
			"type": "metal",
		},
		{
			"id": "LEAD",
			"name": "Lead",
			"color": "#555555",
			"value": 2,
			"type": "metal",
		},
		{
			"id": "ALUMINUM",
			"name": "Aluminum",
			"color": "#FFFFFF",
			"value": 40,
			"type": "metal",
		},
		{
			"id": "NICKEL_SILVER",
			"name": "Nickel silver",
			"color": "#FFFFFF",
			"value": 3,
			"type": "metal",
		},
		{
			"id": "BILLON",
			"name": "Billon",
			"color": "#AAAAAA",
			"value": 6,
			"type": "metal",
		},
		{
			"id": "STERLING_SILVER",
			"name": "Sterling silver",
			"color": "#FFFFFF",
			"value": 8,
			"type": "metal",
		},
		{
			"id": "BLACK_BRONZE",
			"name": "Black bronze",
			"color": "#AA00AA",
			"value": 11,
			"type": "metal",
		},
		{
			"id": "ROSE_GOLD",
			"name": "Rose gold",
			"color": "#FF55FF",
			"value": 23,
			"type": "metal",
		},
		{
			"id": "BISMUTH",
			"name": "Bismuth",
			"color": "#FF55FF",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "BISMUTH_BRONZE",
			"name": "Bismuth bronze",
			"color": "#FFFF55",
			"value": 6,
			"type": "metal",
		},
		{
			"id": "ADAMANTINE",
			"name": "Adamantine",
			"color": "#55FFFF",
			"value": 300,
			"type": "metal",
		},
		{
			"id": "PLASTER",
			"name": "",
			"color": "#FFFFFF",
			"value": 3,
			"type": "stone",
		},
		{
			"id": "CERAMIC_EARTHENWARE",
			"name": "",
			"color": "#AA5500",
			"value": 3,
			"type": "stone",
		},
		{
			"id": "CERAMIC_STONEWARE",
			"name": "",
			"color": "#AAAAAA",
			"value": 4,
			"type": "stone",
		},
		{
			"id": "CERAMIC_PORCELAIN",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "ASH_GLAZE",
			"name": "",
			"color": "#00AAAA",
			"value": 5,
			"type": "stone",
		},
		{
			"id": "TIN_GLAZE",
			"name": "",
			"color": "#00AAAA",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "QUICKLIME",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "MILK_OF_LIME",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "ONYX",
			"name": "",
			"color": "#555555",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "MORION",
			"name": "",
			"color": "#555555",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "SCHORL",
			"name": "",
			"color": "#555555",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "LACE AGATE",
			"name": "",
			"color": "#5555FF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "BLUE JADE",
			"name": "",
			"color": "#5555FF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "LAPIS LAZULI",
			"name": "",
			"color": "#5555FF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "PRASE",
			"name": "",
			"color": "#00AA00",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "PRASE OPAL",
			"name": "",
			"color": "#00AA00",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "BLOODSTONE",
			"name": "",
			"color": "#00AA00",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "MOSS AGATE",
			"name": "",
			"color": "#00AA00",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "MOSS OPAL",
			"name": "",
			"color": "#00AA00",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "VARISCITE",
			"name": "",
			"color": "#00AA00",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "CHRYSOPRASE",
			"name": "",
			"color": "#55FF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "CHRYSOCOLLA",
			"name": "",
			"color": "#55FFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "SARD",
			"name": "",
			"color": "#AA0000",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "CARNELIAN",
			"name": "",
			"color": "#AA0000",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "BANDED AGATE",
			"name": "",
			"color": "#AA0000",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "SARDONYX",
			"name": "",
			"color": "#AA0000",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "CHERRY OPAL",
			"name": "",
			"color": "#FF5555",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "LAVENDER JADE",
			"name": "",
			"color": "#AA00AA",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "PINK JADE",
			"name": "",
			"color": "#FF55FF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "TUBE AGATE",
			"name": "",
			"color": "#AA5500",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "FIRE AGATE",
			"name": "",
			"color": "#AA5500",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "PLUME AGATE",
			"name": "",
			"color": "#AA5500",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "BROWN JASPER",
			"name": "",
			"color": "#AA5500",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "PICTURE JASPER",
			"name": "",
			"color": "#AA5500",
			"value": 3,
			"type": "gem",
		},
		{
			"id": "SMOKY QUARTZ",
			"name": "",
			"color": "#AA5500",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "WAX OPAL",
			"name": "",
			"color": "#AA5500",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "WOOD OPAL",
			"name": "",
			"color": "#AA5500",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "AMBER OPAL",
			"name": "",
			"color": "#AA5500",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "GOLD OPAL",
			"name": "",
			"color": "#FFFF55",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "CITRINE",
			"name": "",
			"color": "#FFFF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "YELLOW JASPER",
			"name": "",
			"color": "#FFFF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "TIGEREYE",
			"name": "",
			"color": "#FFFF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "TIGER IRON",
			"name": "",
			"color": "#FFFF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "SUNSTONE",
			"name": "",
			"color": "#FFFF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "RESIN OPAL",
			"name": "",
			"color": "#FFFF55",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "PYRITE",
			"name": "",
			"color": "#FFFF55",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "CLEAR TOURMALINE",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "GRAY CHALCEDONY",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "DENDRITIC AGATE",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "SHELL OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "BONE OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "WHITE CHALCEDONY",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "FORTIFICATION AGATE",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "MILK QUARTZ",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "MOONSTONE",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "WHITE JADE",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "JASPER OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "PINEAPPLE OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "ONYX OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "MILK OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "PIPE OPAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 10,
			"type": "gem",
		},
		{
			"id": "AVENTURINE",
			"name": "",
			"color": "#00AA00",
			"value": 3,
			"type": "gem",
		},
		{
			"id": "TURQUOISE",
			"name": "",
			"color": "#55FFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "QUARTZ_ROSE",
			"name": "",
			"color": "#FF5555",
			"value": 3,
			"type": "gem",
		},
		{
			"id": "CRYSTAL_ROCK",
			"name": "",
			"color": "#FFFFFF",
			"value": 2,
			"type": "gem",
		},
		{
			"id": "BLACK ZIRCON",
			"name": "",
			"color": "#555555",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "BLACK PYROPE",
			"name": "",
			"color": "#555555",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "MELANITE",
			"name": "",
			"color": "#555555",
			"value": 15,
			"type": "gem",
		},
		{
			"id": "INDIGO TOURMALINE",
			"name": "",
			"color": "#0000AA",
			"value": 25,
			"type": "gem",
		},
		{
			"id": "BLUE GARNET",
			"name": "",
			"color": "#0000AA",
			"value": 30,
			"type": "gem",
		},
		{
			"id": "TSAVORITE",
			"name": "",
			"color": "#00AA00",
			"value": 30,
			"type": "gem",
		},
		{
			"id": "GREEN TOURMALINE",
			"name": "",
			"color": "#00AA00",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "DEMANTOID",
			"name": "",
			"color": "#00AA00",
			"value": 30,
			"type": "gem",
		},
		{
			"id": "GREEN ZIRCON",
			"name": "",
			"color": "#00AA00",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "GREEN JADE",
			"name": "",
			"color": "#55FF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "HELIODOR",
			"name": "",
			"color": "#55FF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "PERIDOT",
			"name": "",
			"color": "#55FF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "RED ZIRCON",
			"name": "",
			"color": "#AA0000",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "RED TOURMALINE",
			"name": "",
			"color": "#AA0000",
			"value": 15,
			"type": "gem",
		},
		{
			"id": "RED PYROPE",
			"name": "",
			"color": "#AA0000",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "ALMANDINE",
			"name": "",
			"color": "#AA0000",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "RED GROSSULAR",
			"name": "",
			"color": "#AA0000",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "PINK TOURMALINE",
			"name": "",
			"color": "#FF5555",
			"value": 15,
			"type": "gem",
		},
		{
			"id": "RED BERYL",
			"name": "",
			"color": "#FF5555",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "FIRE OPAL",
			"name": "",
			"color": "#FF5555",
			"value": 15,
			"type": "gem",
		},
		{
			"id": "RHODOLITE",
			"name": "",
			"color": "#AA00AA",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "SPINEL_PURPLE",
			"name": "",
			"color": "#AA00AA",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "ALEXANDRITE",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "TANZANITE",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "MORGANITE",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "VIOLET SPESSARTINE",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "PINK GARNET",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "KUNZITE",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "CINNAMON GROSSULAR",
			"name": "",
			"color": "#AA5500",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "HONEY YELLOW BERYL",
			"name": "",
			"color": "#AA5500",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "JELLY OPAL",
			"name": "",
			"color": "#AA5500",
			"value": 15,
			"type": "gem",
		},
		{
			"id": "BROWN ZIRCON",
			"name": "",
			"color": "#AA5500",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "YELLOW ZIRCON",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "GOLDEN BERYL",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "YELLOW SPESSARTINE",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "TOPAZ",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "TOPAZOLITE",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "YELLOW GROSSULAR",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "RUBICELLE",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "CLEAR GARNET",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "GOSHENITE",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "CAT'S EYE",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "CLEAR ZIRCON",
			"name": "",
			"color": "#FFFFFF",
			"value": 25,
			"type": "gem",
		},
		{
			"id": "AMETHYST",
			"name": "",
			"color": "#FF55FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "AQUAMARINE",
			"name": "",
			"color": "#55FFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "SPINEL_RED",
			"name": "",
			"color": "#AA0000",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "CHRYSOBERYL",
			"name": "",
			"color": "#55FF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_PFIRE",
			"name": "",
			"color": "#FF5555",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_REDFLASH",
			"name": "",
			"color": "#FF5555",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_BLACK",
			"name": "",
			"color": "#555555",
			"value": 30,
			"type": "gem",
		},
		{
			"id": "OPAL_WHITE",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_CRYSTAL",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_CLARO",
			"name": "",
			"color": "#5555FF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_LEVIN",
			"name": "",
			"color": "#FFFF55",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_HARLEQUIN",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_PINFIRE",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "OPAL_BANDFIRE",
			"name": "",
			"color": "#FFFFFF",
			"value": 20,
			"type": "gem",
		},
		{
			"id": "DIAMOND_LY",
			"name": "",
			"color": "#FFFFFF",
			"value": 30,
			"type": "gem",
		},
		{
			"id": "DIAMOND_FY",
			"name": "",
			"color": "#AA5500",
			"value": 40,
			"type": "gem",
		},
		{
			"id": "EMERALD",
			"name": "",
			"color": "#00AA00",
			"value": 40,
			"type": "gem",
		},
		{
			"id": "RUBY",
			"name": "",
			"color": "#AA0000",
			"value": 40,
			"type": "gem",
		},
		{
			"id": "SAPPHIRE",
			"name": "",
			"color": "#0000AA",
			"value": 40,
			"type": "gem",
		},
		{
			"id": "DIAMOND_CLEAR",
			"name": "",
			"color": "#FFFFFF",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "DIAMOND_RED",
			"name": "",
			"color": "#AA0000",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "DIAMOND_GREEN",
			"name": "",
			"color": "#00AA00",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "DIAMOND_BLUE",
			"name": "",
			"color": "#0000AA",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "DIAMOND_YELLOW",
			"name": "",
			"color": "#FFFF55",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "DIAMOND_BLACK",
			"name": "",
			"color": "#555555",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "SAPPHIRE_STAR",
			"name": "",
			"color": "#5555FF",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "RUBY_STAR",
			"name": "",
			"color": "#FF5555",
			"value": 60,
			"type": "gem",
		},
		{
			"id": "SANDSTONE",
			"name": "Sandstone",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SILTSTONE",
			"name": "Siltstone",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "MUDSTONE",
			"name": "Mudstone",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SHALE",
			"name": "Shale",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CLAYSTONE",
			"name": "Claystone",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ROCK_SALT",
			"name": "Rock salt",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "LIMESTONE",
			"name": "Limestone",
			"color": "#FFFFFF",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "CONGLOMERATE",
			"name": "Conglomerate",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "DOLOMITE",
			"name": "Dolomite",
			"color": "#FFFFFF",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "CHERT",
			"name": "Chert",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CHALK",
			"name": "Chalk",
			"color": "#FFFFFF",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "GRANITE",
			"name": "Granite",
			"color": "#AAAAAA",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "DIORITE",
			"name": "Diorite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "GABBRO",
			"name": "Gabbro",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "RHYOLITE",
			"name": "Rhyolite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "BASALT",
			"name": "Basalt",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ANDESITE",
			"name": "Andesite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "DACITE",
			"name": "Dacite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "OBSIDIAN",
			"name": "Obsidian",
			"color": "#555555",
			"value": 3,
			"type": "stone",
		},
		{
			"id": "QUARTZITE",
			"name": "Quartzite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SLATE",
			"name": "Slate",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PHYLLITE",
			"name": "Phyllite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SCHIST",
			"name": "Schist",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "GNEISS",
			"name": "Gneiss",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "MARBLE",
			"name": "Marble",
			"color": "#FFFFFF",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "HEMATITE",
			"name": "Hematite",
			"color": "#AA0000",
			"value": 8,
			"type": "stone",
		},
		{
			"id": "LIMONITE",
			"name": "Limonite",
			"color": "#FFFF55",
			"value": 8,
			"type": "stone",
		},
		{
			"id": "GARNIERITE",
			"name": "Garnierite",
			"color": "#55FF55",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "NATIVE_GOLD",
			"name": "Native gold dust",
			"color": "#FFFF55",
			"value": 30,
			"type": "stone",
		},
		{
			"id": "NATIVE_SILVER",
			"name": "Native silver",
			"color": "#FFFFFF",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "NATIVE_COPPER",
			"name": "Native copper",
			"color": "#AA5500",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "MALACHITE",
			"name": "Malachite",
			"color": "#00AA00",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "GALENA",
			"name": "Galena",
			"color": "#FFFFFF",
			"value": 5,
			"type": "stone",
		},
		{
			"id": "SPHALERITE",
			"name": "Sphalerite",
			"color": "#555555",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "CASSITERITE",
			"name": "Cassiterite",
			"color": "#AA5500",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "COAL_BITUMINOUS",
			"name": "Bituminous coal",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "LIGNITE",
			"name": "Lignite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "NATIVE_PLATINUM",
			"name": "Native platinum",
			"color": "#FFFFFF",
			"value": 40,
			"type": "stone",
		},
		{
			"id": "CINNABAR",
			"name": "Cinnabar",
			"color": "#FF5555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "COBALTITE",
			"name": "Cobaltite",
			"color": "#5555FF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "TETRAHEDRITE",
			"name": "Tetrahedrite",
			"color": "#555555",
			"value": 3,
			"type": "stone",
		},
		{
			"id": "HORN_SILVER",
			"name": "Horn silver",
			"color": "#FFFFFF",
			"value": 10,
			"type": "stone",
		},
		{
			"id": "GYPSUM",
			"name": "Gypsum",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "TALC",
			"name": "Talc",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "JET",
			"name": "Jet",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PUDDINGSTONE",
			"name": "Puddingstone",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PETRIFIED_WOOD",
			"name": "Petrified wood",
			"color": "#FF5555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "GRAPHITE",
			"name": "Graphite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "BRIMSTONE",
			"name": "Brimstone",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "KIMBERLITE",
			"name": "Kimberlite",
			"color": "#0000AA",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "BISMUTHINITE",
			"name": "Bismuthinite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "REALGAR",
			"name": "Realgar",
			"color": "#FF5555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ORPIMENT",
			"name": "Orpiment",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "STIBNITE",
			"name": "Stibnite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "MARCASITE",
			"name": "Marcasite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SYLVITE",
			"name": "Sylvite",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CRYOLITE",
			"name": "Cryolite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PERICLASE",
			"name": "Periclase",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ILMENITE",
			"name": "Ilmenite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "RUTILE",
			"name": "Rutile",
			"color": "#AA00AA",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "MAGNETITE",
			"name": "Magnetite",
			"color": "#555555",
			"value": 8,
			"type": "stone",
		},
		{
			"id": "CHROMITE",
			"name": "Chromite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PYROLUSITE",
			"name": "Pyrolusite",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PITCHBLENDE",
			"name": "Pitchblende",
			"color": "#AA00AA",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "BAUXITE",
			"name": "Bauxite",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "NATIVE_ALUMINUM",
			"name": "Native aluminum",
			"color": "#FFFFFF",
			"value": 40,
			"type": "stone",
		},
		{
			"id": "BORAX",
			"name": "Borax",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "OLIVINE",
			"name": "Olivine",
			"color": "#00AA00",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "HORNBLENDE",
			"name": "Hornblende",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "KAOLINITE",
			"name": "Kaolinite",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SERPENTINE",
			"name": "Serpentine",
			"color": "#00AA00",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ORTHOCLASE",
			"name": "Orthoclase",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "MICROCLINE",
			"name": "Microcline",
			"color": "#55FFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "MICA",
			"name": "Mica",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CALCITE",
			"name": "Calcite",
			"color": "#FFFFFF",
			"value": 2,
			"type": "stone",
		},
		{
			"id": "SALTPETER",
			"name": "Saltpeter",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ALABASTER",
			"name": "Alabaster",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SELENITE",
			"name": "Selenite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SATINSPAR",
			"name": "Satinspar",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ANHYDRITE",
			"name": "Anhydrite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "ALUNITE",
			"name": "Alunite",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "RAW_ADAMANTINE",
			"name": "Raw adamantine",
			"color": "#55FFFF",
			"value": 250,
			"type": "stone",
		},
		{
			"id": "SLADE",
			"name": "Slade",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CLAY",
			"name": "Clay",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SILTY_CLAY",
			"name": "Silty clay",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SANDY_CLAY",
			"name": "Sandy clay",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CLAY_LOAM",
			"name": "Clay loam",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SANDY_CLAY_LOAM",
			"name": "Sandy clay loam",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SILTY_CLAY_LOAM",
			"name": "Silty clay loam",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "LOAM",
			"name": "Loam",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SANDY_LOAM",
			"name": "Sandy loam",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SILT_LOAM",
			"name": "Silt loam",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "LOAMY_SAND",
			"name": "Loamy sand",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SILT",
			"name": "Silt",
			"color": "#AA5500",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SAND_TAN",
			"name": "Sand",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SAND_YELLOW",
			"name": "Yellow sand",
			"color": "#FFFF55",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SAND_WHITE",
			"name": "White sand",
			"color": "#FFFFFF",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SAND_BLACK",
			"name": "Black sand",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SAND_RED",
			"name": "Red sand",
			"color": "#FF5555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PEAT",
			"name": "Peat",
			"color": "#555555",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "PELAGIC_CLAY",
			"name": "Pelagic clay",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "CALCAREOUS_OOZE",
			"name": "Calcareous ooze",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "SILICEOUS_OOZE",
			"name": "Siliceous ooze",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
		{
			"id": "FIRE_CLAY",
			"name": "Fire clay",
			"color": "#AA0000",
			"value": 1,
			"type": "stone",
		},
	]

static func get_by_id(id: String) -> Dictionary:
	for entry in get_all():
		if entry["id"] == id:
			return entry
	return {}

static func get_names() -> Array:
	var names = []
	for entry in get_all():
		names.append(entry.get("name", ""))
	return names

static func get_with_properties(id: String) -> Dictionary:
	var entry = get_by_id(id)
	if entry.is_empty():
		return {}
	var result = entry.duplicate()
	result["properties"] = DFMaterialProperties.compute(result)
	return result

static func get_all_with_properties() -> Array:
	var result = []
	for entry in get_all():
		var e = entry.duplicate()
		e["properties"] = DFMaterialProperties.compute(e)
		result.append(e)
	return result