# -*- coding: utf-8 -*-
content = []
content.append("# Bigliworld - Roadmap de Desarrollo")
content.append("")
content.append("> Proyecto: Clon de Dwarf Fortress en Godot 4.7")
content.append("> Archivos: 34 scripts GDScript | ~35,934 lineas | ~1.37 MB")
content.append("")
content.append("---")
content.append("")
content.append("## Estado Actual por Sistema")
content.append("")
content.append("| Sistema | Archivo | Estado |")
content.append("|---|---|---|")
content.append("| Generacion de mundo | df_world_gen.gd | OK |")
content.append("| Simulacion historica | df_world_history.gd | OK |")
content.append("| Hidrologia / rios | df_world_hydrology.gd | OK |")
content.append("| Sitios del mundo | df_world_sites.gd | OK |")
content.append("| Materiales y propiedades | df_materials.gd + df_material_properties.gd | OK |")
content.append("| Plantas / ecosistema | df_plants.gd | OK |")
content.append("| Enanos (skills, personalidad, necesidades, emociones) | df_dwarf.gd | OK |")
content.append("| Criaturas (IA, anatomia) | df_creature.gd | OK |")
content.append("| Genetica | df_genetics.gd | OK |")
content.append("| Anatomia | df_anatomy.gd | OK |")
content.append("| Educacion / transmision de conocimiento | df_education.gd | OK |")
content.append("| Items y catalogo | df_item.gd + df_items.gd | OK |")
content.append("| Talleres de produccion | df_workshop.gd | OK |")
content.append("| Trabajos / designaciones | df_job.gd + df_designation.gd | OK |")
content.append("| Almacenes / stockpiles | df_stockpile.gd | OK |")
content.append("| Edificios / construccion | df_building.gd | OK |")
content.append("| Combate (armas, armaduras, heridas) | df_combat.gd | OK |")
content.append("| Militar / ejercito | df_military.gd | OK |")
content.append("| Invasiones | df_invasion.gd | OK |")
content.append("| Caravanas / comercio basico | df_caravan.gd | OK |")
content.append("| Dialogo con NPCs | df_dialogue.gd | OK |")
content.append("| Lore / historia del mundo | df_lore.gd | OK |")
content.append("| Leyendas / cronicas | df_legends.gd | OK |")
content.append("| Misiones procedurales | df_quest.gd | OK |")
content.append("| Figuras historicas | df_historical_figure.gd | OK |")
content.append("| Eventos aleatorios | df_events.gd | OK |")
content.append("| Sistema de consecuencias | df_consequence_system.gd | OK |")
content.append("| Viaje rapido | df_fast_travel.gd | OK |")
content.append("| Guardado / carga | df_save_load.gd | OK |")
content.append("| Audio basico | df_audio.gd | OK |")
content.append("| Cambio de modo (Fortaleza/Aventura/Leyendas) | df_main.gd | OK |")
content.append("| Panel de stats del enano (U) | df_main.gd + df_renderer.gd | OK |")
content.append("| Renderizado ASCII con tiles | df_renderer.gd | OK |")
content.append("")
content.append("---")
content.append("")
content.append("## Roadmap por Fases")
content.append("")
content.append("### FASE 0 - Estabilizacion (Urgente, 1-2 dias)")
content.append("")
content.append("Lo que duele ahora mismo y hace que el juego se sienta roto:")
content.append("")
content.append("| # | Tarea | Por que |")
content.append("|---|-------|---------|")
content.append("| 0.1 | Los enanos no completan trabajos | Cambian de tarea constantemente, no terminan de excavar/talar/construir |")
content.append("| 0.2 | Pataletas frecuentes | Entran en estado pataleta muy rapido. Ajustar umbrales de estres |")
content.append("| 0.3 | Talleres sin produccion real | Se llena de talleres pero no producen nada |")
content.append("| 0.4 | Comida/bebida no funcional | Los enanos no buscan comida activamente a pesar de tener hambre |")
content.append("| 0.5 | Tiempo no avanza visiblemente | Horas/minutos no cambian en pantalla |")
content.append("| 0.6 | Objetos is_table crash | Invalid assignment en RefCounted (DFItem no tiene propiedad is_table) |")
content.append("| 0.7 | 7 enanos atrapados en spawn | A veces aparecen encerrados sin salida |")
content.append("")
content.append("### FASE 1 - Profundidad de Colonia (1 semana)")
content.append("")
content.append("| # | Sistema | Descripcion |")
content.append("|---|---------|-------------|")
content.append("| 1.1 | Muerte y consecuencias reales | Cadaveres que hay que enterrar, fantasmas, herencia de items |")
content.append("| 1.2 | Sistema de justicia | Crimenes, castigos, celdas, ejecuciones |")
content.append("| 1.3 | Mandas nobles | Los nobles exigen habitaciones, objetos, comidas |")
content.append("| 1.4 | Estados de animo extranos | Strange moods: visiones, exigen materiales raros |")
content.append("| 1.5 | Dependencia alcoholica | Sin alcohol -> depresion, rendimiento bajo, muerte |")
content.append("| 1.6 | Ciclo de reproduccion funcional | Nacimientos, infancia, crecimiento, aprendizaje |")
content.append("| 1.7 | Enfermedades y sindromes | Infecciones, plagas, efectos de estado |")
content.append("")
content.append("### FASE 2 - Mundo Vertical (1 semana)")
content.append("")
content.append("| # | Sistema | Descripcion |")
content.append("|---|---------|-------------|")
content.append("| 2.1 | Cavernas subterraneas | 3 capas con ecosistema propio, hongos gigantes |")
content.append("| 2.2 | Bestias olvidadas | Generacion procedural de monstruos unicos |")
content.append("| 2.3 | Magma | Forja, energia y muerte |")
content.append("| 2.4 | Metales preciosos y gemas | Distribucion geologica realista |")
content.append("| 2.5 | Adoquinado / Grabado | Alisar paredes y grabar historia |")
content.append("| 2.6 | Excavacion de habitaciones | Designar zonas: dormitorio, cocina, trono... |")
content.append("| 2.7 | Sistema de agua | Inundaciones, presion hidraulica, molinos |")
content.append("")
content.append("### FASE 3 - Industria y Economia (1 semana)")
content.append("")
content.append("| # | Sistema | Descripcion |")
content.append("|---|---------|-------------|")
content.append("| 3.1 | Cadenas de produccion completas | Mineral -> fundir -> lingote -> forjar -> espada |")
content.append("| 3.2 | Industria textil | Plantas -> fibra -> hilo -> tela -> ropa |")
content.append("| 3.3 | Industria ceramica | Arcilla -> alfareria -> vasijas, ladrillos |")
content.append("| 3.4 | Industria vidriera | Arena -> horno -> vidrio -> ventanas, botellas |")
content.append("| 3.5 | Molinaje | Trigo -> molino -> harina -> pan |")
content.append("| 3.6 | Comercio con caravanas | Precios dinamicos, trueque, exportacion |")
content.append("| 3.7 | Mercado intra-colonia | Enanos compran y venden entre si |")
content.append("")
content.append("### FASE 4 - Guerra y Defensa (1 semana)")
content.append("")
content.append("| # | Sistema | Descripcion |")
content.append("|---|---------|-------------|")
content.append("| 4.1 | Escuadrones militares | Organizar squads, asignar uniformes, entrenamiento |")
content.append("| 4.2 | Armas de asedio | Ballestas, catapultas, torres |")
content.append("| 4.3 | Trampas | Estacas, fosos, puertas levadizas, mecanismos |")
content.append("| 4.4 | Sitiadores | Invasiones con campamentos de asedio |")
content.append("| 4.5 | Puertas y fortificaciones | Muros, murallas, fosos, puentes levadizos |")
content.append("")
content.append("### FASE 5 - Ingenieria y Maquinaria (1 semana)")
content.append("")
content.append("| # | Sistema | Descripcion |")
content.append("|---|---------|-------------|")
content.append("| 5.1 | Energia mecanica | Ruedas hidraulicas, molinos de viento, mecanismos |")
content.append("| 5.2 | Vagonetas / minas | Transporte por rieles |")
content.append("| 5.3 | Compuertas y canales | Control de agua, riego, drenaje |")
content.append("| 5.4 | Mecanismos logicos | Palancas, engranajes, sensores, AND/OR |")
content.append("| 5.5 | Automatizacion | Maquinas que hagan trabajo repetitivo |")
content.append("")
content.append("### FASE 6 - Pulido y Contenido (Continuo)")
content.append("")
content.append("| # | Sistema | Descripcion |")
content.append("|---|---------|-------------|")
content.append("| 6.1 | Efectos de sonido | SFX por accion: talar, cavar, martillar, comer, pelear |")
content.append("| 6.2 | Musica ambiental | Por bioma, profundidad, estacion,
